package com.bookstore.mappers;

import com.bookstore.model.Book;
import com.bookstore.DTOs.BookDTO;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.factory.Mappers;

@Mapper(componentModel = "spring")
public interface BookMapper {
    BookDTO toDTO(Book book);

    @Mapping(target = "id", ignore = true) // id is generated by DB
    Book toEntity(BookDTO bookDTO);

}
